[env]
TERM = "xterm-256color"

[colors]
draw_bold_text_with_bright_colors = true

# neobones

[colors.bright]
black = "#263945"
red = "#E8838F"
green = "#A0FF85"
yellow = "#D68C67"
blue = "#92A0E2"
magenta = "#CF86C1"
cyan = "#65B8C1"
white = "#98A39E"

[colors.cursor]
cursor = "#CEDDD7"
text = "#0F191F"

[colors.normal]
black = "#0F191F"
blue = "#8190D4"
cyan = "#66A5AD"
green = "#90FF6B"
magenta = "#B279A7"
red = "#DE6E7C"
white = "#C6D5CF"
yellow = "#B77E64"

[colors.primary]
background = "#0F191F"
foreground = "#C6D5CF"

# The classic Terminal look.
# https://github.com/alacritty/alacritty-theme/blob/master/themes/terminal_app.toml

# # Default colors
# [colors.primary]
# background = '#000000'
# foreground = '#b6b6b6'
#
# # Normal colors
# [colors.normal]
# black   = '#000000'
# red     = '#990000'
# green   = '#00a600'
# yellow  = '#999900'
# blue    = '#0000b2'
# magenta = '#b200b2'
# cyan    = '#00a6b2'
# white   = '#bfbfbf'
#
# # Bright colors
# [colors.bright]
# black   = '#666666'
# red     = '#e50000'
# green   = '#00d900'
# yellow  = '#e5e500'
# blue    = '#0000ff'
# magenta = '#e500e5'
# cyan    = '#00e5e5'
# white   = '#e5e5e5'
#
# Neovim colours for terminal below.

# [colors.cursor]
# text = "#14161b"
# cursor = "#E0E2EA"

# [colors.vi_mode_cursor]
# text = "#14161b"
# cursor = "#E0E2EA"

# [colors.search.matches]
# foreground = "#14161b"
# background = "#4f5258"

# [colors.search.focused_match]
# foreground = "#14161b"
# background = "#7EDFDE"

# [colors.footer_bar]
# foreground = "#14161b"
# background = "#7EDFDE"

# [colors.hints.start]
# foreground = "#14161b"
# background = "#E5ADB9"

# [colors.hints.end]
# foreground = "#14161b"
# background = "#7EDFDE"

# [colors.selection]
# text = "#E0E2EA"
# background = "#4f5258"

# [colors.normal]
# black = "#2c2e33"
# red = "#E5ADB9"
# green = "#A2DFC0"
# yellow = "#E3CA85"
# blue = "#95C5E5"
# magenta = "#E5B6E6"
# cyan = "#7EDFDE"
# white = "#C4C6CD"
#
# [colors.bright]
# black = "#4f5258"
# red = "#FFC0B9"
# green = "#B4F6C0"
# yellow = "#FCE094"
# blue = "#A6DBFF"
# magenta = "#FFCAFF"
# cyan = "#8CF8F7"
# white = "#9b9ea4"
#
# [colors.dim]
# black = "#2c2e33"
# red = "#E5ADB9"
# green = "#A2DFC0"
# yellow = "#E3CA85"
# blue = "#95C5E5"
# magenta = "#E5B6E6"
# cyan = "#7EDFDE"
# white = "#C4C6CD"

# [[colors.indexed_colors]]
# index = 16
# color = "#7EDFDE"
#
# [[colors.indexed_colors]]
# index = 17
# color = "#4f5258"

## Font configuration
[font]
size = 13.0

[font.bold]
family = "JetBrains Mono NL"
style = "Bold"

[font.italic]
family = "JetBrains Mono NL"
style = "Italic"

[font.normal]
family = "JetBrains Mono NL"
style = "Regular"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Alt"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Alt"

[window]
decorations = "full"
startup_mode = "Maximized"
