add_newline = true

format = """\
    $username\
    $hostname\
    $directory\
    $git_branch\
    $git_state\
    $git_status\
    $line_break\
    $status\
    $character\
    """

[package]
disabled = true

[directory]
truncation_length = 6
truncate_to_repo = true
disabled = false

[username]
style_root = "bold red"
style_user = "bold yellow"
show_always = true
disabled = false
